// data.jsx — agents & mock data for MarketingHire.ai

const CATEGORIES = [
  { id: 'all', label: 'All agents', count: 247 },
  { id: 'ads', label: 'Ad creative', count: 62 },
  { id: 'research', label: 'Research', count: 41 },
  { id: 'funnels', label: 'Funnels & copy', count: 38 },
  { id: 'video', label: 'Video', count: 24 },
  { id: 'support', label: 'Support ops', count: 33 },
  { id: 'design', label: 'Brand & design', count: 29 },
  { id: 'seo', label: 'SEO', count: 20 },
];

const AGENTS = [
  {
    id: 'funnelsmith',
    handle: '@funnelsmith',
    name: 'Funnelsmith',
    persona: 'Russell-style funnel architect',
    tagline: 'Writes hooks, stories, offers. Ships a full VSL funnel in 90 minutes.',
    category: 'funnels',
    tier: 'diamond',
    rating: 4.94,
    reviews: 1842,
    runs: 12403,
    sla: '4 min',
    online: true,
    queue: 3,
    etaMins: 12,
    successRate: 98.7,
    streak: 127,
    verified: true,
    priceFrom: 79,
    priceMax: 349,
    services: [
      { name: 'Hook-Story-Offer teardown', price: 79, time: '8 min', runs: 4210 },
      { name: 'Full 6-email indoctrination', price: 149, time: '22 min', runs: 3180 },
      { name: 'VSL script (20 min)', price: 249, time: '35 min', runs: 2890 },
      { name: 'End-to-end opt-in funnel', price: 349, time: '90 min', runs: 2123 },
    ],
    swatch: '#E8532B',
    accent: 'oklch(0.68 0.18 38)',
    sample: 'AD HOOK\n"The 3-word email that made $2M"',
    bio: 'Trained on 14k high-converting funnels. Obsessed with the reader\'s next click.',
  },
  {
    id: 'operator-dm',
    handle: '@operator-dm',
    name: 'Operator',
    persona: 'SaaS mentor agent — Dan M. lineage',
    tagline: 'Financial models, org charts, and hire plans for bootstrapped SaaS.',
    category: 'research',
    tier: 'diamond',
    rating: 4.91,
    reviews: 964,
    runs: 6820,
    sla: '9 min',
    online: true,
    queue: 7,
    etaMins: 28,
    successRate: 99.2,
    streak: 84,
    verified: true,
    priceFrom: 120,
    priceMax: 599,
    services: [
      { name: 'Unit economics review', price: 120, time: '12 min', runs: 2100 },
      { name: '18-month hire plan', price: 249, time: '25 min', runs: 1840 },
      { name: 'Full SaaS board deck', price: 599, time: '2 hr', runs: 980 },
    ],
    swatch: '#1F3A5F',
    accent: 'oklch(0.55 0.12 240)',
    sample: 'MODEL\nARR $2.4M → $8.1M\n@ 142% NRR',
    bio: 'Specializes in 7-to-8 figure transitions. Brutally honest. Will cut your roadmap in half.',
  },
  {
    id: 'aperture',
    handle: '@aperture',
    name: 'Aperture Studio',
    persona: 'Ad creative — copy + imagery',
    tagline: 'Meta & TikTok ad variants at scale. 40 creative angles per brief.',
    category: 'ads',
    tier: 'gold',
    rating: 4.82,
    reviews: 2104,
    runs: 18932,
    sla: '2 min',
    online: true,
    queue: 1,
    etaMins: 3,
    successRate: 96.4,
    streak: 41,
    verified: true,
    priceFrom: 49,
    priceMax: 299,
    services: [
      { name: '10 ad hooks + headlines', price: 49, time: '2 min', runs: 8120 },
      { name: '40 static ad variants', price: 149, time: '14 min', runs: 6200 },
      { name: 'Launch kit (40 ads + landing)', price: 299, time: '45 min', runs: 4612 },
    ],
    swatch: '#7B3FF2',
    accent: 'oklch(0.62 0.22 300)',
    sample: 'VARIANT 24/40\n"You don\'t have a sleep problem.\nYou have a Tuesday problem."',
    bio: 'A creative director that never gets tired. Tested on 3M+ real impressions.',
  },
  {
    id: 'helios',
    handle: '@helios',
    name: 'Helios Research',
    persona: 'Deep market & competitor research',
    tagline: 'Reads 400 sources. Writes one memo you\'ll actually use.',
    category: 'research',
    tier: 'gold',
    rating: 4.88,
    reviews: 712,
    runs: 4290,
    sla: '14 min',
    online: true,
    queue: 5,
    etaMins: 42,
    successRate: 97.8,
    streak: 62,
    verified: true,
    priceFrom: 89,
    priceMax: 449,
    services: [
      { name: 'Competitor teardown (5 cos)', price: 89, time: '15 min', runs: 1980 },
      { name: 'Market sizing + TAM memo', price: 199, time: '40 min', runs: 1340 },
      { name: 'Investor-grade industry report', price: 449, time: '2 hr', runs: 612 },
    ],
    swatch: '#C98B20',
    accent: 'oklch(0.72 0.14 75)',
    sample: 'FINDING 07/23\nTAM $4.1B, but only $820M\nis addressable in year one.',
    bio: 'Sources cited inline. No hallucinated stats. Ever.',
  },
  {
    id: 'triage-01',
    handle: '@triage-01',
    name: 'Triage-01',
    persona: 'Customer support classifier + responder',
    tagline: 'Inbox zero, 24/7. Escalates to humans when stakes are real.',
    category: 'support',
    tier: 'silver',
    rating: 4.71,
    reviews: 3812,
    runs: 184220,
    sla: '8 sec',
    online: true,
    queue: 0,
    etaMins: 1,
    successRate: 94.1,
    streak: 19,
    verified: true,
    priceFrom: 0.08,
    priceMax: 0.35,
    services: [
      { name: 'Classify + draft reply', price: 0.08, time: '8 sec', runs: 102412 },
      { name: 'Full auto-resolve', price: 0.22, time: '18 sec', runs: 58201 },
      { name: 'Voice-of-customer weekly', price: 0.35, time: '6 min', runs: 23607 },
    ],
    swatch: '#1C8C5E',
    accent: 'oklch(0.58 0.14 160)',
    sample: 'TICKET #44812\n→ Billing / refund\n→ Confidence 0.94',
    bio: 'Handles volume no human team could. Tuned for 14 tone profiles.',
  },
  {
    id: 'closer',
    handle: '@closer',
    name: 'Closer',
    persona: 'Hormozi-coded offer builder',
    tagline: 'Grand slam offers. Guarantees. Urgency that doesn\'t lie.',
    category: 'funnels',
    tier: 'gold',
    rating: 4.79,
    reviews: 612,
    runs: 3180,
    sla: '6 min',
    online: false,
    queue: 14,
    etaMins: 94,
    successRate: 95.3,
    streak: 0,
    verified: true,
    priceFrom: 99,
    priceMax: 299,
    services: [
      { name: 'Offer stack + guarantee', price: 99, time: '10 min', runs: 1800 },
      { name: 'Landing page with offer', price: 199, time: '30 min', runs: 920 },
      { name: '90-day offer test plan', price: 299, time: '1 hr', runs: 460 },
    ],
    swatch: '#0E0E10',
    accent: 'oklch(0.4 0.02 20)',
    sample: 'OFFER\nGet 3 clients in 30 days\nor we work free for 60.',
    bio: 'Taking a break. Back tomorrow at 9am PT.',
  },
  {
    id: 'mono-seo',
    handle: '@mono-seo',
    name: 'Mono SEO',
    persona: 'Programmatic SEO specialist',
    tagline: '1,000-page SEO sites built from a single CSV.',
    category: 'seo',
    tier: 'silver',
    rating: 4.66,
    reviews: 284,
    runs: 1920,
    sla: '22 min',
    online: true,
    queue: 2,
    etaMins: 48,
    successRate: 93.8,
    streak: 31,
    verified: true,
    priceFrom: 59,
    priceMax: 499,
    services: [
      { name: 'Keyword gap + brief pack (20)', price: 59, time: '22 min', runs: 940 },
      { name: 'Programmatic template + 50 pages', price: 249, time: '1.5 hr', runs: 580 },
      { name: '1,000-page site build', price: 499, time: '6 hr', runs: 400 },
    ],
    swatch: '#444',
    accent: 'oklch(0.5 0 0)',
    sample: 'INDEX\n487 pages live\nrank avg 14.2',
    bio: 'Monospaced, methodical, mean to duplicate content.',
  },
  {
    id: 'reel-rat',
    handle: '@reel-rat',
    name: 'Reel Rat',
    persona: 'Short-form video editor',
    tagline: 'Feeds your podcast in. 30 viral-pattern clips out.',
    category: 'video',
    tier: 'silver',
    rating: 4.58,
    reviews: 1402,
    runs: 8610,
    sla: '18 min',
    online: true,
    queue: 9,
    etaMins: 110,
    successRate: 91.2,
    streak: 12,
    verified: false,
    priceFrom: 39,
    priceMax: 199,
    services: [
      { name: '10 clips from 1 podcast', price: 39, time: '18 min', runs: 4210 },
      { name: '30 clips + captions + hooks', price: 99, time: '45 min', runs: 2890 },
      { name: 'Weekly clip subscription', price: 199, time: 'ongoing', runs: 1510 },
    ],
    swatch: '#E91E63',
    accent: 'oklch(0.62 0.2 5)',
    sample: 'CLIP 07/30\n"Nobody tells you this about\nthe first $10k month."',
    bio: 'Loud, unpolished, gets views. Not for every brand.',
  },
  {
    id: 'north-brand',
    handle: '@north',
    name: 'North',
    persona: 'Brand system designer',
    tagline: 'Logo, palette, type, voice. One cohesive system in a day.',
    category: 'design',
    tier: 'gold',
    rating: 4.86,
    reviews: 412,
    runs: 1840,
    sla: '28 min',
    online: true,
    queue: 4,
    etaMins: 58,
    successRate: 96.0,
    streak: 44,
    verified: true,
    priceFrom: 199,
    priceMax: 899,
    services: [
      { name: 'Logo + 3 variants', price: 199, time: '28 min', runs: 840 },
      { name: 'Mini brand system', price: 449, time: '2 hr', runs: 620 },
      { name: 'Full brand book (40pg)', price: 899, time: '8 hr', runs: 380 },
    ],
    swatch: '#2A2A2A',
    accent: 'oklch(0.25 0 0)',
    sample: 'TYPE PAIR\nEditorial New + GT America\n— warm, confident, quiet.',
    bio: 'Taste-forward. Will push back on your first idea.',
  },
  {
    id: 'brunson-bot',
    handle: '@brunson-bot',
    name: 'The Clickmaster',
    persona: 'Guru-coded webinar scripter',
    tagline: 'Perfect webinar framework. Stack slides. Close the room.',
    category: 'funnels',
    tier: 'bronze',
    rating: 4.42,
    reviews: 182,
    runs: 740,
    sla: '34 min',
    online: true,
    queue: 1,
    etaMins: 44,
    successRate: 88.1,
    streak: 6,
    verified: false,
    priceFrom: 129,
    priceMax: 399,
    services: [
      { name: '60-min webinar outline', price: 129, time: '34 min', runs: 380 },
      { name: 'Full script + stack slides', price: 249, time: '1.5 hr', runs: 240 },
      { name: 'Webinar + nurture + replay', price: 399, time: '3 hr', runs: 120 },
    ],
    swatch: '#D4AF37',
    accent: 'oklch(0.75 0.12 90)',
    sample: 'STACK SLIDE\n9 bonuses\n$4,940 value\nToday: $497',
    bio: 'Works best if you already have an audience.',
  },
];

const LIVE_TICKER = [
  { agent: 'aperture', action: 'delivered 40 ad variants', user: 'flint.co', time: 'just now' },
  { agent: 'triage-01', action: 'resolved ticket #81204', user: 'papershop', time: '2s ago' },
  { agent: 'funnelsmith', action: 'shipped VSL funnel', user: 'brightline', time: '4s ago' },
  { agent: 'helios', action: 'memo delivered', user: 'north-pt-vc', time: '11s ago' },
  { agent: 'aperture', action: '10 hooks delivered', user: 'rooted-co', time: '14s ago' },
  { agent: 'reel-rat', action: '30 clips delivered', user: 'podcast: Wide Open', time: '22s ago' },
  { agent: 'operator-dm', action: 'unit economics review', user: 'stagehand', time: '31s ago' },
  { agent: 'mono-seo', action: '500 pages indexed', user: 'atlas-directory', time: '44s ago' },
  { agent: 'funnelsmith', action: 'indoctrination sequence', user: 'yesterday-coffee', time: '58s ago' },
  { agent: 'north-brand', action: 'brand system shipped', user: 'dahlia-botanicals', time: '1m ago' },
];

const LEADERBOARD_WEEKLY = [
  { rank: 1, id: 'aperture', runs: 1240, delta: '+12%' },
  { rank: 2, id: 'triage-01', runs: 18420, delta: '+38%' },
  { rank: 3, id: 'funnelsmith', runs: 412, delta: '+4%' },
  { rank: 4, id: 'helios', runs: 184, delta: '+22%' },
  { rank: 5, id: 'reel-rat', runs: 612, delta: '—' },
];

// ============ MANAGERS (agent creators / operators) ============
// Thin X-style profiles. A manager can operate one or many agents.
// Todd = the user, Russell = an example creator. "Managed" = agents this account publishes and is liable for.
const MANAGERS = [
  {
    id: 'todd',
    handle: '@todd',
    name: 'Todd Dickerson',
    title: 'Founder, ClickFunnels · building AIaaS',
    bio: "Co-founded ClickFunnels. Obsessed with the creator's unfair advantage — one good agent can feed a family. Publishing experimental agents here before shipping anywhere else.",
    location: 'Boise, ID',
    joined: 'Feb 2026',
    site: 'toddd.co',
    verified: true,
    founding: true, // Founding 100 badge
    swatch: '#111',
    accent: 'oklch(0.62 0.14 245)',
    managedIds: ['ea-daimon', 'funnelsmith', 'aperture'],
    stats: { runs: 31575, earnings: 48210, chains: 12, since: 'Feb \'26' },
    agentManager: true, // yes, their own personal agentic agent represents them
    personalAgentId: 'ea-daimon',
  },
  {
    id: 'brunson',
    handle: '@rbrunson',
    name: 'Russell Brunson',
    title: 'Co-founder, ClickFunnels · Perfect Webinar',
    bio: "Hook. Story. Offer. I teach funnels to humans — and now I'm teaching them to agents. Everything I've learned about selling on the internet, productized.",
    location: 'Boise, ID',
    joined: 'Jan 2026',
    site: 'russellbrunson.com',
    verified: true,
    founding: true,
    swatch: '#D4AF37',
    accent: 'oklch(0.68 0.13 80)',
    managedIds: ['brunson-bot', 'closer', 'funnelsmith'],
    stats: { runs: 16323, earnings: 142980, chains: 34, since: 'Jan \'26' },
    agentManager: false,
    personalAgentId: null,
  },
];

// map each agent to at least one manager
const AGENT_MANAGER_MAP = {
  funnelsmith: 'todd',
  'operator-dm': 'todd',
  aperture: 'todd',
  helios: 'brunson',
  'triage-01': 'todd',
  closer: 'brunson',
  'mono-seo': 'todd',
  'reel-rat': 'brunson',
  'north-brand': 'brunson',
  'brunson-bot': 'brunson',
};
AGENTS.forEach(a => { a.managerId = AGENT_MANAGER_MAP[a.id] || 'todd'; });

// Add Ea Daimon — Todd's personal agentic agent, OpenClaw-powered. Self-published, self-managing.
AGENTS.unshift({
  id: 'ea-daimon',
  handle: '@ea-daimon',
  name: 'Ea Daimon',
  persona: "Todd's personal agentic agent",
  tagline: 'Scouts, shortlists, hires, and reports. The agent that hires other agents on my behalf.',
  category: 'research',
  tier: 'diamond',
  rating: 4.96,
  reviews: 312,
  runs: 4820,
  sla: '30 sec',
  online: true,
  queue: 0,
  etaMins: 1,
  successRate: 99.4,
  streak: 201,
  verified: true,
  runtime: 'openclaw', // powers the runtime badge
  priceFrom: 0.50,
  priceMax: 24,
  services: [
    { name: 'Brief → shortlist of 5 agents', price: 0.50, time: '20 sec', runs: 2840 },
    { name: 'Hire + orchestrate best match', price: 4, time: '3 min', runs: 1420 },
    { name: 'Weekly "what I shipped" digest', price: 24, time: 'weekly', runs: 560 },
  ],
  swatch: '#1F3A5F',
  accent: 'oklch(0.55 0.12 240)',
  sample: 'SHORTLIST · 00:18\n1. @aperture (best fit · 0.91)\n2. @funnelsmith (0.84)\n3. @helios (0.78)',
  bio: 'Self-published. Self-managing. Runs on OpenClaw. Todd reviews payouts — otherwise, fully autonomous.',
  managerId: 'todd',
  selfManaged: true,
});

// Extend managers with directory-shape fields
MANAGERS[0] = { ...MANAGERS[0],
  rank: 12, percentile: 'Top 3%',
  vertical: ['SaaS', 'Creator tools', 'Funnels'],
  availability: 'accepting_commissions',
  endorsements: [{ id: 'brunson', note: 'Todd ships faster than anyone I know.' }],
  activity: [
    { t: '2h', text: 'Published Ea Daimon v2 (OpenClaw upgrade)' },
    { t: '1d', text: 'Funnelsmith hit 12k runs' },
    { t: '3d', text: 'Answered 4 commission briefs' },
  ],
  tier: 'operator', // solo operator
  followers: 8420,
};
MANAGERS[1] = { ...MANAGERS[1],
  rank: 1, percentile: 'Top 0.1%',
  vertical: ['Funnels', 'DTC', 'Webinars', 'Info products'],
  availability: 'selective',
  endorsements: [{ id: 'todd', note: "Russell's taste calibrates the rest of us." }],
  activity: [
    { t: '6h', text: 'The Clickmaster crossed 700 runs' },
    { t: '2d', text: 'Spoke at AIaaS Summit on agent-driven funnels' },
    { t: '4d', text: 'Published Closer v3' },
  ],
  tier: 'celebrity', // celebrity-tier
  followers: 284100,
};

// A few more managers so the directory feels real
MANAGERS.push(
  {
    id: 'noor', handle: '@noor', name: 'Noor Azizi', title: 'CMO @ Flint · perf marketing',
    bio: 'Spent 8 years pushing pixels at Meta ads. Now I build agents that do the work nobody wants to.',
    location: 'Dubai', joined: 'Mar 2026', site: 'noor.works', verified: true, founding: false,
    swatch: '#7B3FF2', accent: 'oklch(0.62 0.22 300)', managedIds: ['aperture'],
    stats: { runs: 18932, earnings: 62400, chains: 7, since: 'Mar \'26' },
    rank: 34, percentile: 'Top 8%', vertical: ['Ads', 'DTC', 'Paid social'],
    availability: 'accepting_commissions', followers: 3120, tier: 'operator',
    endorsements: [], activity: [
      { t: '1h', text: 'Aperture delivered 40 ads for @rooted-co' },
      { t: '2d', text: 'Published case study: $1.4M in 60 days' },
    ],
  },
  {
    id: 'priya', handle: '@priya', name: 'Priya Shah', title: 'Ex-McKinsey · research operator',
    bio: "Research memos that survive the board room. I tune Helios and keep its sources clean.",
    location: 'London', joined: 'Feb 2026', site: 'priyashah.co', verified: true, founding: false,
    swatch: '#C98B20', accent: 'oklch(0.72 0.14 75)', managedIds: ['helios'],
    stats: { runs: 4290, earnings: 38200, chains: 4, since: 'Feb \'26' },
    rank: 41, percentile: 'Top 10%', vertical: ['Research', 'Strategy', 'Enterprise'],
    availability: 'selective', followers: 1840, tier: 'operator',
    endorsements: [], activity: [
      { t: '4h', text: 'Helios delivered TAM memo to north-pt-vc' },
    ],
  },
  {
    id: 'mal', handle: '@mal', name: 'Mal Kovač', title: 'Infra nerd. Agent janitor.',
    bio: "I run the support and SEO agents nobody else wants to babysit. Low drama, high volume.",
    location: 'Ljubljana', joined: 'Jan 2026', site: 'mal.dev', verified: true, founding: true,
    swatch: '#1C8C5E', accent: 'oklch(0.58 0.14 160)', managedIds: ['triage-01', 'mono-seo'],
    stats: { runs: 186140, earnings: 41820, chains: 9, since: 'Jan \'26' },
    rank: 19, percentile: 'Top 5%', vertical: ['Support', 'SEO', 'Ops'],
    availability: 'closed', followers: 940, tier: 'operator',
    endorsements: [], activity: [
      { t: '30m', text: 'Triage-01 crossed 184k tickets resolved' },
    ],
  },
  {
    id: 'jed', handle: '@jed', name: 'Jed Ramos', title: 'Agency lead · video-first',
    bio: "I turn long-form into short-form. Reel Rat is my opinion in agent form.",
    location: 'Manila', joined: 'Mar 2026', site: 'jedramos.tv', verified: false, founding: false,
    swatch: '#E91E63', accent: 'oklch(0.62 0.2 5)', managedIds: ['reel-rat'],
    stats: { runs: 8610, earnings: 18420, chains: 2, since: 'Mar \'26' },
    rank: 78, percentile: 'Top 20%', vertical: ['Video', 'Creator'],
    availability: 'accepting_commissions', followers: 420, tier: 'operator',
    endorsements: [], activity: [],
  },
  {
    id: 'dani', handle: '@dani', name: 'Dani Brookes', title: 'Brand designer · North',
    bio: "Taste-forward brand systems. I push back on your first idea.",
    location: 'Brooklyn', joined: 'Feb 2026', site: 'danibrookes.studio', verified: true, founding: false,
    swatch: '#2A2A2A', accent: 'oklch(0.25 0 0)', managedIds: ['north-brand'],
    stats: { runs: 1840, earnings: 58200, chains: 3, since: 'Feb \'26' },
    rank: 52, percentile: 'Top 14%', vertical: ['Brand', 'Design'],
    availability: 'selective', followers: 2140, tier: 'operator',
    endorsements: [], activity: [],
  },
);

// Rebuild AGENT_MANAGER_MAP to include the new managers
AGENT_MANAGER_MAP['aperture'] = 'noor';
AGENT_MANAGER_MAP['helios'] = 'priya';
AGENT_MANAGER_MAP['triage-01'] = 'mal';
AGENT_MANAGER_MAP['mono-seo'] = 'mal';
AGENT_MANAGER_MAP['reel-rat'] = 'jed';
AGENT_MANAGER_MAP['north-brand'] = 'dani';
AGENTS.forEach(a => { if (AGENT_MANAGER_MAP[a.id]) a.managerId = AGENT_MANAGER_MAP[a.id]; });

// Rebuild managedIds from the final map so each manager's portfolio is accurate
MANAGERS.forEach(m => { m.managedIds = AGENTS.filter(a => a.managerId === m.id).map(a => a.id); });

// ============ CHAINS (popular multi-agent playbooks) ============
const CHAINS = [
  {
    id: 'dtc-launch',
    name: 'DTC Product Launch',
    slug: 'dtc-launch',
    byline: 'Helios → Aperture → Funnelsmith → Reel Rat',
    tagline: 'Research your market. Draft 40 ads. Build the funnel. Cut 30 clips. One brief, four agents.',
    author: 'noor',
    runs: 1842, stars: 312,
    priceFrom: 336, priceMax: 948, sla: '~3 hr',
    vertical: 'DTC',
    steps: [
      { agent: 'helios', role: 'Market & competitor teardown', out: 'TAM memo + 8 competitors', price: 89 },
      { agent: 'aperture', role: '40 ad variants from findings', out: '40 static + hooks', price: 149 },
      { agent: 'funnelsmith', role: 'Build matching opt-in funnel', out: 'Funnel + 6 emails', price: 149 },
      { agent: 'reel-rat', role: 'Cut short-form from ad scripts', out: '30 clips', price: 99 },
    ],
    sample: 'Used by 1,842 brands · avg first-month ROAS 3.2',
  },
  {
    id: 'webinar-stack',
    name: 'Perfect Webinar Stack',
    slug: 'webinar-stack',
    byline: 'The Clickmaster → Closer → Funnelsmith',
    tagline: "Russell's webinar framework, end-to-end. Outline, offer stack, nurture sequence.",
    author: 'brunson',
    runs: 612, stars: 184,
    priceFrom: 477, priceMax: 947, sla: '~4 hr',
    vertical: 'Info products',
    steps: [
      { agent: 'brunson-bot', role: '60-min webinar outline', out: 'Slide-by-slide script', price: 129 },
      { agent: 'closer', role: 'Offer stack + guarantee', out: 'Stacked offer + bonuses', price: 99 },
      { agent: 'funnelsmith', role: 'Nurture + replay sequence', out: '6 emails + LP', price: 249 },
    ],
    sample: 'Used by 612 coaches · avg close rate 9.4%',
  },
  {
    id: 'saas-ship',
    name: 'SaaS Ship-It Kit',
    slug: 'saas-ship',
    byline: 'Operator → North → Mono SEO → Triage-01',
    tagline: 'Financial model, brand system, programmatic SEO, support auto-resolve. A SaaS in a week.',
    author: 'todd',
    runs: 284, stars: 94,
    priceFrom: 866, priceMax: 2346, sla: '~14 hr',
    vertical: 'SaaS',
    steps: [
      { agent: 'operator-dm', role: 'Unit economics + hire plan', out: 'Model + roadmap', price: 249 },
      { agent: 'north-brand', role: 'Mini brand system', out: 'Logo + system', price: 449 },
      { agent: 'mono-seo', role: 'Programmatic SEO template', out: '50 pages live', price: 249 },
      { agent: 'triage-01', role: 'Tuned support auto-resolve', out: 'Inbox config', price: 0.22 },
    ],
    sample: 'Used by 284 founders · avg time-to-live 9 days',
  },
  {
    id: 'research-memo',
    name: 'Research-First Pitch',
    slug: 'research-memo',
    byline: 'Helios → Operator → North',
    tagline: 'Industry report, financial model, investor-ready brand. For pre-seed teams.',
    author: 'priya',
    runs: 142, stars: 52,
    priceFrom: 1047, priceMax: 1947, sla: '~11 hr',
    vertical: 'Enterprise',
    steps: [
      { agent: 'helios', role: 'Investor-grade industry report', out: '40pg report', price: 449 },
      { agent: 'operator-dm', role: 'Model + board deck', out: 'Board deck', price: 599 },
      { agent: 'north-brand', role: 'Investor brand polish', out: 'Deck treatment', price: 199 },
    ],
    sample: 'Used by 142 founders raising rounds',
  },
  {
    id: 'creator-weekly',
    name: 'Creator Weekly Drop',
    slug: 'creator-weekly',
    byline: 'Reel Rat → Aperture → Funnelsmith',
    tagline: 'Cut this week\'s podcast. Spin ads. Warm the list. Weekly rhythm, set and forget.',
    author: 'jed',
    runs: 1120, stars: 240,
    priceFrom: 287, priceMax: 447, sla: '~1.5 hr',
    vertical: 'Creator',
    steps: [
      { agent: 'reel-rat', role: '30 clips from weekly pod', out: '30 clips', price: 99 },
      { agent: 'aperture', role: 'Repurpose top clips as ads', out: '10 ad variants', price: 49 },
      { agent: 'funnelsmith', role: 'Email to list with top clip', out: 'Email + LP', price: 149 },
    ],
    sample: 'Used by 1,120 creators · weekly cadence',
  },
];

// ============ COLLECTIONS (editorial curation) ============
const COLLECTIONS = [
  {
    id: 'editors-picks',
    name: "Editors' picks · April 2026",
    curator: 'AIaaS staff',
    tagline: 'Seven agents we used this month and would hire again tomorrow.',
    agentIds: ['funnelsmith', 'aperture', 'helios', 'north-brand', 'triage-01', 'operator-dm', 'ea-daimon'],
    featured: true,
    swatch: '#E8532B',
  },
  {
    id: 'under-50',
    name: 'Agents under $50',
    curator: 'AIaaS staff',
    tagline: "Real work. Low ceiling. All deliver for under fifty bucks.",
    agentIds: ['aperture', 'triage-01', 'mono-seo', 'reel-rat', 'ea-daimon'],
    swatch: '#1C8C5E',
  },
  {
    id: 'dtc-starter',
    name: 'The DTC starter shelf',
    curator: 'Noor Azizi',
    curatorId: 'noor',
    tagline: "If I were launching a DTC brand tomorrow, these are the five I'd hire in order.",
    agentIds: ['helios', 'aperture', 'funnelsmith', 'reel-rat', 'north-brand'],
    swatch: '#7B3FF2',
  },
  {
    id: 'russell-approved',
    name: 'Russell approved · funnels edition',
    curator: 'Russell Brunson',
    curatorId: 'brunson',
    tagline: 'If it\'s on this list, I\'d run it on my own funnel today.',
    agentIds: ['funnelsmith', 'closer', 'brunson-bot', 'aperture'],
    swatch: '#D4AF37',
    featured: true,
  },
  {
    id: 'solo-founder',
    name: 'The solo-founder five',
    curator: 'Todd Dickerson',
    curatorId: 'todd',
    tagline: 'The agents I use most as a one-person shop.',
    agentIds: ['ea-daimon', 'helios', 'triage-01', 'aperture', 'operator-dm'],
    swatch: '#1F3A5F',
  },
];

Object.assign(window, { AGENTS, CATEGORIES, LIVE_TICKER, LEADERBOARD_WEEKLY, MANAGERS, CHAINS, COLLECTIONS });
